### ISSUE TITLE
Potential for concurrent access to internal type cache

### ISSUE THREAD

**Issue by Hawxy** [soenneker/soenneker.utils.autobogus#381]
Hiya,
We had some tests recently start failing with the below stack trace:
```
  07:20:58 [DBG]   Error Message:
  07:20:58 [DBG]    System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  07:20:58 [DBG]   Stack Trace:
  07:20:58 [DBG]      at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
  07:20:58 [DBG]    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
  07:20:58 [DBG]    at Soenneker.Utils.AutoBogus.AutoFakerBinder.GetConstructor(CachedType cachedType)
  07:20:58 [DBG]    at Soenneker.Utils.AutoBogus.AutoFakerBinder.CreateInstance[TType](AutoFakerContext context, CachedType cachedType)
  07:20:58 [DBG]    at Soenneker.Utils.AutoBogus.Generators.Types.TypeGenerator`1.Soenneker.Utils.AutoBogus.Generators.Abstract.IAutoFakerGenerator.Generate(AutoFakerContext context)
  07:20:58 [DBG]    at Soenneker.Utils.AutoBogus.Extensions.AutoGenerateContextExtension.Generate[TType](AutoFakerContext context)
  07:20:58 [DBG]    at Soenneker.Utils.AutoBogus.AutoFaker.Generate[TType]()
```

Our test suite is heavily parallelized, and it appears something attempted to write to the cache mid-read. Should the cache be using a concurrent dictionary internally?

**Comment by soenneker** [comment]
@Hawxy Thanks for creating this issue

Should be fixed with latest version.
